server:
  port: 9000

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/library_jbdl33?createDatabaseIfNotExist=true
    username: root
    password:

custom:
  my_prop: hello_world
